module.exports={
    PRODUCT_COLLECTIONS:'product',
    USER_COLLECTIONS:'user',
    ADMIN_COLLECTIONS:'admin',
    CATEGORY_COLLECTIONS:'category',
    CART_COLLECTIONS:'cart',
    ORDER_COLLECTIONS:'order',
    COUPON_COLLECTION:'coupon'
}